azext_edge/constants.py
azext_edge/edge/providers/base.py
azext_edge/edge/providers/orchestration/base.py
azext_edge/edge/providers/stats.py
azext_edge/tests/edge/mq/test_stats_unit.py

fix(trace): ensure expected bytes are fetched

---

azext_edge/constants.py
azext_edge/edge/providers/support/base.py
azext_edge/edge/providers/support/orc.py
azext_edge/tests/edge/support/test_support_unit.py

* Additionally increment build version.

fix: Temp use field selector to capture orc service missing label

---

README.md
azext_edge/constants.py
azext_edge/edge/_help.py
azext_edge/edge/params.py
azext_edge/edge/providers/orchestration/base.py
azext_edge/edge/providers/orchestration/template.py
azext_edge/edge/providers/orchestration/work.py
azext_edge/edge/providers/support/akri.py
azext_edge/edge/providers/support/base.py
azext_edge/edge/providers/support/opcua.py
azext_edge/edge/providers/support/orc.py
azext_edge/tests/edge/init/conftest.py
azext_edge/tests/edge/init/test_work_unit.py
azext_edge/tests/edge/support/conftest.py
azext_edge/tests/edge/support/test_support_unit.py

* Includes refactor for support bundle due to akri daemonset name changes and orchestrator service filling label gap.

feat: template updates (and related support bundle changes) + help content

---

azext_edge/edge/providers/orchestration/base.py
azext_edge/edge/providers/orchestration/work.py

Also ensures pre-flight non-success status is raised if not handled by resource client.

fix: improve error mode when CSI driver deployment mismatches kubeconfig cluster

---

azext_edge/edge/providers/support/base.py
azext_edge/edge/providers/support/otel.py
azext_edge/edge/providers/support_bundle.py
azext_edge/tests/edge/support/test_support_unit.py

feat: add sb integration for aio otel deployment 

---

.github/workflows/release_build.yml
.github/workflows/release_workflow.yml
.github/workflows/upload_wheel.yml

Our principal is already set up with access to the storage account, AzCopy only needs the two env vars set:
- AZCOPY_AUTO_LOGIN_TYPE: "AZCLI"
- AZCOPY_TENANT_ID
`azcopy list` now has a `quiet` param because by default it prints info / debug output about the auto login.
--- …

chore(ci): use service principal identity for wheel uploads

---

azext_edge/tests/edge/support/create_bundle_int/test_auto_int.py

chore: temporary fix support bundle testing for billing

---

azext_edge/constants.py
azext_edge/edge/providers/orchestration/template.py
azext_edge/tests/edge/init/test_template_unit.py
tools/template_optimizer.py

* Includes further updates to `template_optimizer.py` to streamline integration.

feat: Update built-in template to 0.5.0-preview

---

azext_edge/edge/providers/stats.py
azext_edge/tests/edge/mq/test_stats_unit.py

fix: Validate diagnostics pod is in running phase prior to connection

---

azext_edge/tests/edge/init/test_work_unit.py

test: add case for template param conversion of include_dp

---

azext_edge/edge/providers/check/base/resource.py
azext_edge/edge/providers/checks.py
azext_edge/tests/edge/checks/int/test_pre_post_int.py

Reverts Azure/azure-iot-ops-cli-extension#241

revert: error when expected CRD is not deployed instead of skip

---

azext_edge/edge/_help.py
azext_edge/edge/command_map.py
azext_edge/edge/commands_edge.py
azext_edge/edge/params.py
azext_edge/edge/providers/orchestration/instances.py
azext_edge/edge/util/az_client.py
azext_edge/edge/vendor/clients/iotopsmgmt/_client.py
azext_edge/edge/vendor/clients/iotopsmgmt/_configuration.py
azext_edge/edge/vendor/clients/iotopsmgmt/operations/__init__.py
azext_edge/edge/vendor/clients/iotopsmgmt/operations/_operations.py
azext_edge/tests/conftest.py
azext_edge/tests/edge/orchestration/test_instance_unit.py

* Removes deprecated parameter `--custom-location-namespace`.
* Also refreshes iotopsmgmt client.

feat: Adds instance update.

---

azext_edge/edge/providers/base.py
azext_edge/edge/util/__init__.py
azext_edge/edge/util/common.py
azext_edge/tests/utility/test_common_unit.py
azext_edge/tests/utility/test_file_operations_unit.py

* Minimum set of changes to re-enable broker stats trace functionality.
* Re-factors an existing similar util function test.

fix: Update stats trace functionality to work with 0.6.0 broker

---

azext_edge/edge/providers/edge_api/__init__.py
azext_edge/edge/providers/edge_api/meta.py
azext_edge/edge/providers/support/base.py
azext_edge/edge/providers/support/billing.py
azext_edge/edge/providers/support/meta.py
azext_edge/edge/providers/support_bundle.py
azext_edge/tests/edge/support/create_bundle_int/helpers.py
azext_edge/tests/edge/support/create_bundle_int/test_auto_int.py
azext_edge/tests/edge/support/create_bundle_int/test_meta_int.py
azext_edge/tests/edge/support/test_support_unit.py

feat: Capture meta operator in support bundle

---

.github/workflows/codeql.yml

chore: update codeql action version to v3

---

azext_edge/constants.py
azext_edge/edge/providers/orchestration/work.py
azext_edge/tests/edge/init/test_work_unit.py

* This will be short-lived, as the deployment is changing.

fix: casing issue in target name

---

azext_edge/edge/providers/orchestration/resources/schema_registries.py
azext_edge/tests/edge/orchestration/resources/test_schema_registry_unit.py
setup.py

* Identified some issues with help from @Elsie4ever.

refactor: explicit azure-mgmt-storage dep + temp do not run permission_manager.can_apply_role_assignment

---

azext_edge/edge/common.py
azext_edge/edge/providers/orchestration/common.py
azext_edge/edge/providers/orchestration/targets.py
azext_edge/edge/providers/orchestration/template.py

* Note default endpoint.
* Note default resource name changes.

refactor: Another refresh of templates

---

azext_edge/constants.py
azext_edge/edge/providers/orchestration/targets.py
azext_edge/edge/util/az_client.py

refactor: schema reg id handle in targets

---

azext_edge/constants.py
azext_edge/edge/providers/stats.py
azext_edge/tests/edge/mq/test_stats_unit.py

fix: stats phase casing

---

dev_requirements.txt

chore: sync dev with feature/0.7.0

---

azext_edge/edge/providers/orchestration/targets.py

fix: remove trust config placeholder

---

.pylintrc

chore: sync feature/0.7.0 with dev

---

azext_edge/constants.py
azext_edge/edge/_help.py
azext_edge/edge/commands_edge.py
azext_edge/edge/params.py
azext_edge/edge/providers/orchestration/targets.py
azext_edge/edge/providers/orchestration/template.py
azext_edge/edge/util/az_client.py

* Includes fix for fetch of the schema registry by init to use the newest API.

refactor: template refresh + skip deploying rsr by default + various improves

---

.github/workflows/int_test.yml
azext_edge/tests/edge/init/int/test_init_int.py

going to merge into this branch to test out the changes first
---

test: update instance create tests to incorporate broker config files and enable rsync

---

azext_edge/edge/providers/orchestration/work.py

* Reduce potential issues from propagation delay.

refactor: add principalType for AIO ext -> SR role assignment

---

azext_edge/edge/common.py
azext_edge/tests/edge/rpsaas/adr/conftest.py
azext_edge/tests/edge/rpsaas/adr/test_asset_endpoint_profiles_unit.py

* From OpcUa -> Microsoft.OpcUa

refactor: Change OPCUA AEP connector type value 

---

azext_edge/constants.py
azext_edge/edge/_help.py
azext_edge/edge/command_map.py
azext_edge/edge/commands_edge.py
azext_edge/edge/providers/orchestration/upgrade.py
azext_edge/tests/edge/orchestration/test_upgrade_unit.py

min version supported => 1.0.6
no need for instance update anymore
TODO: put in env variable
---
A PR is considered **ready for review** when all basic expectations have …

feat: update upgrade for GA

---

azext_edge/edge/_help.py
azext_edge/edge/providers/edge_api/__init__.py
azext_edge/edge/providers/edge_api/certmanager.py
azext_edge/edge/providers/support_bundle.py
azext_edge/tests/edge/support/create_bundle_int/test_certmanager_int.py

there is one more api in cert manager: trust.cert-manager.io/v1alpha1 that contains trust bundle CR, therefore adding it as a fix
---
A PR is considered **ready for review** …

fix: add trust bundle CR in cert manager

---

azext_edge/edge/_help.py
azext_edge/edge/commands_edge.py
azext_edge/edge/providers/orchestration/upgrade2.py
azext_edge/edge/util/__init__.py
azext_edge/tests/edge/orchestration/test_upgrade2_unit.py
azext_edge/tests/edge/orchestration/test_work_unit.py

* Adds confirm prompt to mitigate broker not being able to upgrade when backend replaces are < 2.
* Upgrade UX, skip table render when no upgrade available.

fix: adds confirm prompt to mitigate broker upgrade issue

---

azext_edge/constants.py
azext_edge/edge/_help.py
azext_edge/edge/providers/orchestration/resources/instances.py
azext_edge/edge/providers/rpsaas/adr/params.py

* And show -> list text fix for user warning if secretsync already enabled.

docs: secretsync enable help improve

---

azext_edge/constants.py
azext_edge/edge/commands_edge.py
azext_edge/edge/params.py
azext_edge/edge/providers/orchestration/upgrade2.py
azext_edge/tests/edge/orchestration/test_upgrade2_unit.py

* Hidden flag `--force` is added to override the block if necessary.

feat!: block downgrade

---

.github/workflows/int_test.yml
azext_edge/tests/edge/orchestration/test_upgrade_int.py
azext_edge/tests/edge/support/create_bundle_int/helpers.py
azext_edge/tests/edge/support/create_bundle_int/test_auto_int.py
pytest.ini.example

refactor: Improve integration tests

---

azext_edge/edge/_help.py
azext_edge/edge/common.py
azext_edge/edge/providers/check/opcua.py
azext_edge/edge/providers/check/summary.py
azext_edge/edge/providers/checks.py
azext_edge/edge/providers/support/connectors.py
azext_edge/edge/providers/support_bundle.py
azext_edge/tests/edge/support/create_bundle_int/test_connectors_int.py
azext_edge/tests/edge/support/test_connectors_unit.py
azext_edge/tests/edge/support/test_support_unit.py

Rename opcua to connectors due to all connectors resources will be allocated in one place in future
---
A PR is considered **ready for review** when all basic expectations …

refactor: support bundle rename opcua to connectors

---

azext_edge/constants.py
azext_edge/edge/_help.py
azext_edge/edge/command_map.py
azext_edge/edge/commands_mq.py
azext_edge/edge/params.py
azext_edge/edge/providers/orchestration/resources/brokers.py
azext_edge/edge/providers/orchestration/resources/instances.py
azext_edge/edge/providers/orchestration/resources/reskit.py
azext_edge/tests/edge/orchestration/resources/conftest.py
azext_edge/tests/edge/orchestration/resources/test_broker_listeners_unit.py

* +feat: hide/deprecate broker delete.

feat: listener create/replace min.

---

.azure-devops/merge.yml
.github/workflows/release_build.yml
.github/workflows/release_workflow.yml

- Sets up a simple merge pipeline in ADO for governance
- Adds pip feed authentication to install tasks for release pipeline
The build pipeline now requires one additional secret, `PIP_FEED_URL` to point to our artifact feed.
---
Azure IoT Operations CLI maintainers …

chore(ci): Pipeline updates

---

azext_edge/edge/commands_edge.py
azext_edge/edge/providers/orchestration/__init__.py
azext_edge/edge/providers/orchestration/clone.py

* Also removes an unnecessary param from clone split deployment.

fix: cffi conflict

---

azext_edge/constants.py
azext_edge/edge/providers/orchestration/upgrade2.py
azext_edge/edge/util/machinery.py
azext_edge/tests/edge/orchestration/test_upgrade2_unit.py
setup.py
thirdpartynotice

* Adds new util module for non-standard import related elements. The introduced functionality is one example; another is dynamic import of modules via importlib machinery due to special use cases.
* Goal is to eventually eliminate the `packaging` runtime dependency.

feat: extend version string compatibility, apply to upgrade

---

azext_edge/constants.py
azext_edge/edge/_help.py
azext_edge/edge/commands_secretsync.py
azext_edge/edge/params.py
azext_edge/edge/providers/orchestration/resources/instances.py
azext_edge/tests/edge/orchestration/resources/conftest.py
azext_edge/tests/edge/orchestration/resources/test_clusters_unit.py
azext_edge/tests/edge/orchestration/resources/test_instances_unit.py
azext_edge/tests/edge/orchestration/resources/test_secretsync_spcs_unit.py
azext_edge/tests/edge/orchestration/test_clone_unit.py
azext_edge/tests/generators.py

* Added support for tags on default SPC via --tags.
* Added support for custom role via --custom-role-id.

feat!: secretsync enable should raise error if role assignment fails + new functionality

---

.github/actions/connect-arc/action.yml
.github/workflows/int_test.yml
azext_edge/constants.py
azext_edge/edge/_help.py
azext_edge/edge/command_map.py
azext_edge/edge/commands_dataflow.py
azext_edge/edge/commands_edge.py
azext_edge/edge/commands_secretsync.py
azext_edge/edge/params.py
azext_edge/edge/providers/orchestration/clone.py
azext_edge/edge/providers/orchestration/common.py
azext_edge/edge/providers/orchestration/resources/dataflows.py
azext_edge/edge/providers/orchestration/resources/instances.py
azext_edge/edge/providers/orchestration/template.py
azext_edge/edge/util/__init__.py
azext_edge/edge/util/common.py
azext_edge/tests/edge/orchestration/resources/conftest.py
azext_edge/tests/edge/orchestration/resources/test_broker_authns_unit.py
azext_edge/tests/edge/orchestration/resources/test_broker_authzs_unit.py
azext_edge/tests/edge/orchestration/resources/test_broker_listeners_unit.py
azext_edge/tests/edge/orchestration/resources/test_brokers_unit.py
azext_edge/tests/edge/orchestration/resources/test_clusters_unit.py
azext_edge/tests/edge/orchestration/resources/test_dataflow_endpoints_unit.py
azext_edge/tests/edge/orchestration/resources/test_dataflow_profiles_unit.py
azext_edge/tests/edge/orchestration/resources/test_dataflows_unit.py
azext_edge/tests/edge/orchestration/resources/test_instances_unit.py
azext_edge/tests/edge/orchestration/resources/test_secretsync_spcs_unit.py
azext_edge/tests/edge/orchestration/test_clone_unit.py
azext_edge/tests/edge/orchestration/test_secretsync_int.py
azext_edge/tests/generators.py

chore: update branch to dev
