azext_edge/edge/providers/check/base.py, azext_edge/edge/providers/check/common.py, azext_edge/edge/providers/check/lnm.py, azext_edge/edge/providers/edge_api/lnm.py, azext_edge/tests/edge/checks/conftest.py, azext_edge/tests/edge/support/conftest.py
1. add exclude subresource flag to enumerate_ops_service_resources so individual service can decide to exclude enumerate subresource or not
2. as discussion we will hide all subresources from showing under lnm service check (current behaviour -- only scale is showing but status is not)
After fix:
---
Intent for …
=> fix: Add exclude subresource list and exclude subresources showing from lnm check

azext_edge/edge/commands_edge.py, azext_edge/edge/params.py, azext_edge/edge/providers/stats.py, azext_edge/edge/providers/support/base.py, azext_edge/edge/providers/support/mq.py, azext_edge/edge/providers/support_bundle.py, azext_edge/tests/edge/mq/test_stats_unit.py, azext_edge/tests/edge/support/conftest.py, azext_edge/tests/edge/support/test_support_unit.py
* This PR introduces the optional `--mq-traces` flag to `az iot ops support create-bundle`.
* This is a convenience/shortcut, as the `stats` command supports both fetching traces by `--trace-ids` or `--trace-dir`. 
* Also smooths out some tcp socket byte handling.
=> feat: --mq-traces in support bundle operation

azext_edge/edge/params.py, azext_edge/edge/providers/check/base.py, azext_edge/edge/providers/check/common.py, azext_edge/edge/providers/check/dataprocessor.py, azext_edge/edge/providers/check/lnm.py, azext_edge/edge/providers/check/opcua.py, azext_edge/edge/providers/checks.py, azext_edge/tests/edge/checks/conftest.py, azext_edge/tests/edge/checks/test_lnm_checks_unit.py, azext_edge/tests/edge/checks/test_opcua_checks_unit.py
Add opcua asset type check
level 0 output:
level 1 output:
level 2 output:
---
A PR is considered **ready for review** when all basic expectations have been met (or do not …
=> feat: add opcua asset type check

azext_edge/edge/_help.py, azext_edge/edge/command_map.py, azext_edge/edge/commands_assets.py
Fixing the polling for asset lists exposes an issue with RPSaaS object versioning and breaks list overall. Thus, this command will just be removed and we will point users at the query.
Issue with versioning:
The subscriptions have assets created with a previous API version, that have been created with a different schema (i.e., connectivityProfileUri vs assetEndpointProfileUri) and this fails the swagger validation when returning the resources
Also note that query will just return everything in resource graph - even if it was created with older API's 👯 
---
This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact …
=> refactor: remove `az iot ops asset list`

azext_edge/constants.py, azext_edge/edge/providers/orchestration/base.py, azext_edge/edge/util/az_client.py, azext_edge/edge/util/common.py, setup.cfg
- When importing azure namespace packages, ensures extension packages are first on namespace pkg path and sys.path.
- Add placeholder SPC for `aio-opc-ua-broker-issuer-list`.
=> feat: Use ensure_azure_namespace_path() + add placeholder SPC. 

.github/workflows/azdev_linter.yml, .github/workflows/ci_build.yml, .github/workflows/ci_workflow.yml, .github/workflows/cluster_cleanup.yml, .github/workflows/codeql.yml, .github/workflows/int_test.yml, .github/workflows/release_build.yml, .github/workflows/release_workflow.yml, .github/workflows/security_checks.yml, .github/workflows/stage_release.yml, .github/workflows/tox.yml, .github/workflows/update_private_index.yml, .github/workflows/upload_wheel.yml
Workflow updates:
- Explicit permissions blocks to support `GITHUB_TOKEN` as `read` by default
- Update node 16 actions to node 20 versions where possible
- [Azure/login](https://github.com/Azure/login/issues/357) and [microsoft/security-devops-action](https://github.com/microsoft/security-devops-action/issues/89) have issues pending
- Update SBOM tool version
- Add `-v` switch to cluster resource cleanup commands to alleviate API-version restrictions in `az resource delete` 
---
This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any additional …
=> ci: explicit workflow permissions blocks, update action versions to node 20 versions, cluster cleanup fix

README.md, azext_edge/constants.py, azext_edge/edge/_help.py, azext_edge/edge/providers/orchestration/permissions.py, azext_edge/edge/providers/orchestration/template.py, azext_edge/edge/providers/orchestration/work.py, azext_edge/tests/edge/init/conftest.py, azext_edge/tests/edge/init/test_permissions_unit.py, azext_edge/tests/edge/init/test_template_unit.py, azext_edge/tests/edge/init/test_work_unit.py
* Doc improvements for readme, verify-host example and clearer error for RSR permission check.
* +Permission check unit test content and addition of one more valid form of permission `*/write`.
*  WorkManager.build_template() gets and modifies deep copy of base template.
* Increment version.
=> fix: improve docs + modify copy of template

azext_edge/edge/providers/support/base.py, azext_edge/tests/edge/support/conftest.py, azext_edge/tests/edge/support/test_support_unit.py
* Rather than namespaced events capture cluster wide events. Main driver is deployment failures where using the existing support bundle has likelihood of not capturing events due to dependence of mq broker instances to determine which namespaces to pull events from.
=> refactor: SB capture cluster wide events

azext_edge/edge/providers/orchestration/base.py, azext_edge/edge/providers/orchestration/common.py, azext_edge/edge/providers/orchestration/host.py, azext_edge/tests/edge/conftest.py, azext_edge/tests/edge/init/test_base_unit.py
Looked at the base file and made some tests.
one of the shortest prs in a while
---
A PR is considered **ready for review** when all basic expectations have been met (or do …
=> test: adds test content for orchestration provider

azext_edge/edge/params.py
Before:
after:
Note: I added a set so if the services decide to use the same name again it will be caught in the set...
---
A PR is considered **ready for review** when all …
=> fix: remove duplicate choice for parameter in `az iot ops check`

.github/workflows/cluster_cleanup.yml, .github/workflows/int_test.yml
Adds the following matrix strategy to our integration test workflow to configure AIO init feature sets:
```yaml
strategy:
matrix:
feature: [default, mq-ins, syncrules, ca-certs]
include:
- feature: default
ca-valid-days: 3
kv-sat-secret-name: test-kv-secret
- feature: mq-ins
mq-insecure: true
no-preflight: true
- feature: syncrules
disable-rsync-rules: true
- feature: ca-certs
ca-file: 'test-ca.pem'
ca-key-file: 'test-ca-key.pem'
```
This allows us to spin up multiple clusters to test various init configurations.
In this example, each string in `feature: [default...]` are the feature sets, and any extra options under `include` for that feature are matrix options added to that `feature`.
The resulting test matrix looks like this:
```
[
{ feature: 'mq-ins', mq-insecure: true, no-preflight: …
```
=> ci: Add matrix strategy / feature set for init integration tests

.github/workflows/cluster_cleanup.yml, .github/workflows/int_test.yml
=> fix(ci): Int tests - remove continue-on-fail and add second az login to update token

azext_edge/edge/providers/support/akri.py, azext_edge/tests/edge/support/conftest.py, azext_edge/tests/edge/support/test_support_unit.py
Finally labels for everything
example bundle:
---
=> fix: update akri labels for `az iot ops support create-bundle`

azext_edge/edge/providers/check/common.py, azext_edge/edge/providers/check/dataprocessor.py, azext_edge/edge/providers/support/dataprocessor.py, azext_edge/tests/edge/support/test_support_unit.py
for support bundle: remove the label for no longer existed pod, and remove some code that seems to get repetitive resource
for check: remove the label for no longer existed pod
---
Azure IoT Operations CLI maintainers reserve the right to enforce any of the outlined …
=> refactor: update dp support bundle and checks for new 0.4.0 template

azext_edge/edge/providers/check/akri.py, azext_edge/edge/providers/support/akri.py
Now I feel like I could have slipped this in the other pr...
---
=> fix: tweak akri for `az iot ops check`

azext_edge/edge/providers/check/opcua.py
Add check for opcua-asset-discovery pod
---
=> fix: Add check for opcua-asset-discovery pod

azext_edge/edge/providers/check/akri.py, azext_edge/edge/providers/check/base.py, azext_edge/tests/edge/checks/test_base_helpers_unit.py
Also found a nested error (it resolved itself by now) so added some flavor color:
---
A PR is considered **ready for review** when all basic expectations have been met (or …
=> fix: make `az iot ops check` find nested errors

azext_edge/edge/providers/check/common.py, azext_edge/edge/providers/check/dataprocessor.py, azext_edge/tests/edge/checks/test_dataprocessor_checks_unit.py
This pr added further support for dataprocessor check(dataprocessor service as source of truth):
1. Updated some properties in processor stages
2. Added blob storage, file and http destination type for dp pipeline
3. Refacted some common used code
level 0:
level 1:
level 2:
---
Basic …
=> fix: Add support for dataprocessor stage type

azext_edge/edge/providers/k8s/cluster_role_binding.py, azext_edge/edge/providers/orchestration/base.py, azext_edge/tests/edge/init/test_base_unit.py
* For reasons AKS-EE has issues with direct-lookup of the target mixed case cluster role binding via proxy. This issue does not repro against arc-connected k3s via proxy. Refactoring to field selector allows consistent results including against AKS-EE.
=> refactor: Change pre-check for custom locations feature to use field selector 

azext_edge/constants.py, azext_edge/edge/providers/k8s/config_map.py, azext_edge/edge/providers/orchestration/base.py, azext_edge/edge/providers/orchestration/common.py, azext_edge/edge/providers/orchestration/work.py, azext_edge/tests/edge/init/conftest.py, azext_edge/tests/edge/init/test_base_unit.py, azext_edge/tests/edge/init/test_work_unit.py
=> feat: verify cluster arc config as routed by kubeconfig matches target cloud connected cluster

azext_edge/edge/providers/orchestration/base.py, azext_edge/tests/edge/init/test_base_unit.py
* As well as template `location` parameter if not provided.
* Primary driver is usage of `--template-file` with the standard template which includes a lower cased allow list of locations. Pre-flight errors occur if the actual cluster location is of mixed case.
=> refactor: use lower case cluster location for template clusterLocation

azext_edge/edge/commands_edge.py, azext_edge/edge/common.py, azext_edge/edge/params.py, azext_edge/edge/providers/orchestration/base.py, azext_edge/edge/providers/orchestration/template.py, azext_edge/edge/providers/orchestration/work.py, azext_edge/tests/edge/init/conftest.py, azext_edge/tests/edge/init/test_base_unit.py, azext_edge/tests/edge/init/test_work_unit.py
* Refactor step presentation for Pre-Flight stage
* Also tweak how the "Deploy IoT Operations" stage looks.
* Adds an (asterisk) indicator for which step is in work.
* Backfills some gaps in presentation layer unit tests.
* Changes how disabling pre-flight stage works. Uses env var over CLI parameter to reduce visibility and disincentivize usage.
* The generated test only CA + key do not get written to disk by default. Instead the user must use `--ca-dir` i.e. `--ca-dir .`
* Swaps green variable indicators with cyan.
=> feat: init ux layer improvements + refactors

azext_edge/edge/providers/check/opcua.py
Adding a label + removing unused labels to catch pods that were not captured.
---
A PR is considered **ready for review** when all basic expectations have been met (or do …
=> fix: tweak labels used for OPCUA checks (for v0.5.0)

azext_edge/edge/providers/check/akri.py, azext_edge/edge/providers/check/common.py, azext_edge/edge/providers/check/dataprocessor.py, azext_edge/edge/providers/check/mq.py, azext_edge/edge/providers/support/akri.py
This pr updated the labels in checks besides OPC UA, to fix the issue that some pods were not captured in new 0.5.0 template
---
A PR is considered **ready for review** when …
=> fix: update labels in checks for services

azext_edge/edge/providers/support/orc.py, azext_edge/tests/edge/support/test_support_unit.py
* Can no longer rely on the instance name as that has a generated suffix.
=> fix: orchestrator labels for 0.5.0 support bundle

azext_edge/tests/edge/support/create_bundle_int/helpers.py
Trying to use a different method to determine namespaces + add in some logging for tests
Added in fixes for tests running on windows (with explanations in comments)
---
A PR …
=> test: some improvements to support bundle integration tests

azext_edge/edge/providers/check/common.py, azext_edge/tests/edge/support/create_bundle_int/helpers.py
According to https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-conditions
---
A PR is considered **ready for review** when all basic expectations have …
=> fix: Update pod condition in checks

.github/workflows/int_test.yml, azext_edge/tests/edge/support/create_bundle_int/test_auto_int.py
1. limit test_create_bundle inputs
2. add in durations=0 for timing ease
---
A PR is considered **ready for review** when all basic expectations have been met (or do not …
=> test: improvements for integration tests

azext_edge/edge/providers/check/base/__init__.py, azext_edge/edge/providers/check/base/pod.py, azext_edge/edge/providers/check/common.py, azext_edge/edge/providers/check/lnm.py, azext_edge/tests/edge/checks/base/test_pod_unit.py, azext_edge/tests/edge/checks/conftest.py
1. Add unit tests for pod functions
2. Moved a function for the pod check refactor preparation post release
ps: will do more refactoring function-wise post release
---
A PR …
=> refactor: add pod related unit tests

azext_edge/tests/edge/support/create_bundle_int/helpers.py
Added in some gets to make sure that if the pod, etc is not present, it won't destroy the rest of the test. The name checks still ensures that if there are no pods, then the support bundle also reports no pods.
Note the lack of billing pods:
---
Azure IoT Operations CLI …
=> test: fix support bundle integration tests to allow no pods

azext_edge/edge/_help.py, azext_edge/edge/params.py, azext_edge/edge/providers/rpsaas/adr/assets.py, azext_edge/edge/providers/rpsaas/adr/user_strings.py, azext_edge/tests/edge/rpsaas/adr/asset/test_asset_lifecycle_int.py, azext_edge/tests/edge/rpsaas/adr/asset/test_data_points_unit.py, azext_edge/tests/edge/rpsaas/adr/asset/test_events_unit.py, azext_edge/tests/edge/rpsaas/adr/asset/test_helpers_unit.py, azext_edge/tests/edge/rpsaas/adr/asset_profile/test_asset_endpoint_lifecycle_int.py, azext_edge/tests/edge/rpsaas/adr/conftest.py, cluster_query.json
This does the following:
1. fix the `az iot ops asset update` custom attribute param
2. make the cli check if the asset data point or event has a valid observability mode and set the default to "none" (without having to wait for the service to do so)
4. "fix" up the integration tests to include cluster/custom location resource groups
Too tired to think of a meme so here is a deer:
---
This checklist is …
=> fix: improve error functionality for asset data-point and event observability mode

azext_edge/tests/edge/support/create_bundle_int/helpers.py, azext_edge/tests/edge/support/create_bundle_int/test_auto_int.py, azext_edge/tests/edge/support/create_bundle_int/test_dataprocessor_int.py, azext_edge/tests/edge/support/create_bundle_int/test_opcua_int.py
Fixes:
1. DP is now optional (will skip test/remove the key)
2. pod metrics is now optional
idk how I got this into the azure fork but will be more careful
---
A PR is …
=> test(support bundles): make data processor and pod metrics optional

azext_edge/tests/edge/support/create_bundle_int/test_auto_int.py, azext_edge/tests/edge/support/create_bundle_int/test_lnm_int.py
test failed when there is no lnm instance and try to find resource against running "kubectl get lnm -A"
therefore adding null check before find resource in kubectl output
---
Azure IoT Operations CLI maintainers reserve the right to enforce any of the outlined …
=> fix: IT add null check for run("kubectl get lnm -A") in support bundle

azext_edge/tests/edge/checks/int/__init__.py, azext_edge/tests/edge/checks/int/helpers.py, azext_edge/tests/edge/checks/int/test_akri_int.py, azext_edge/tests/edge/checks/int/test_opcua_int.py, azext_edge/tests/edge/checks/int/test_pre_post_int.py, azext_edge/tests/edge/support/create_bundle_int/helpers.py, azext_edge/tests/edge/support/create_bundle_int/test_auto_int.py, azext_edge/tests/edge/support/create_bundle_int/test_mq_int.py, azext_edge/tests/helpers.py
... now I have to copy paste my work...
Akri check integration tests
1. organize check integration tests
2. set up helpers for other service check tests (opcua, mq)
3. see that `--as-object` needs love
Future tasks:
1. improve akri checks --as-object
2. improve opcua checks --as-object
3. add mq check int tests
5. fill out pre check int test
---
This checklist is used to make sure that common guidelines …
=> test: integration tests for akri and opcua checks

azext_edge/tests/edge/checks/int/helpers.py, azext_edge/tests/edge/checks/int/test_pre_post_int.py
Change the pre/post test to ensure that the pre checks test the correct thing.
Success
Warning
Error
---
A PR is considered **ready for review** when all basic expectations …
=> test: `az iot ops check --pre` updates

azext_edge/edge/providers/check/base/resource.py, azext_edge/edge/providers/checks.py, azext_edge/tests/edge/checks/int/test_pre_post_int.py
error when expected CRD is not deployed instead of skip
fix color code showing in --as-object title
before fix:
after fix:
---
A PR is considered **ready for review** when …
=> fix: error when expected CRD is not deployed instead of skip

azext_edge/edge/_help.py, azext_edge/edge/commands_edge.py, azext_edge/edge/common.py, azext_edge/edge/params.py, azext_edge/edge/providers/edge_api/__init__.py, azext_edge/edge/providers/edge_api/mq.py, azext_edge/edge/providers/support/base.py, azext_edge/edge/providers/support/mq.py, azext_edge/edge/providers/support/orc.py, azext_edge/edge/providers/support_bundle.py, azext_edge/tests/edge/checks/conftest.py, azext_edge/tests/edge/checks/test_mq_checks_unit.py, azext_edge/tests/edge/support/conftest.py, azext_edge/tests/edge/support/create_bundle_int/test_auto_int.py, azext_edge/tests/edge/support/create_bundle_int/test_mq_int.py, azext_edge/tests/edge/support/test_support_unit.py
1. update support bundle from mq to mqttbroker, update api group and resource capture
2. int test also caught an error of orc label change, therefore also updated the label
---
Azure IoT Operations CLI maintainers reserve the right to enforce any of the outlined …
=> feat: update support bundle to adapt change for mqttbroker

azext_edge/edge/common.py, azext_edge/edge/providers/rpsaas/adr/base.py, azext_edge/edge/providers/rpsaas/base_provider.py, azext_edge/edge/providers/rpsaas/user_strings.py, azext_edge/tests/edge/rpsaas/base/provider/test_check_cluster_and_custom_location_unit.py, azext_edge/tests/edge/rpsaas/base/provider/test_check_cluster_connectivity_unit.py
Changed the RPSAAS extension check to see if "microsoft.iotoperations" is present and if "adr.enabled" is true.
quick and easy
---
A PR is considered **ready for review** …
=> fix: update cluster extension check for assets and endpoints

azext_edge/edge/providers/support/base.py, azext_edge/edge/providers/support/shared.py, azext_edge/tests/edge/support/conftest.py, azext_edge/tests/edge/support/test_support_unit.py
* Captures azure-clusterconfig config map as a means to easily associate edge side with cloud side. Also useful details such as arc agent version.
* Also has a minor breaking change on renaming the archived storage_classes.yaml to storage-classes.yaml for consistency.
=> feat: Capture azure cluster config in support bundle

azext_edge/edge/_help.py, azext_edge/edge/common.py, azext_edge/edge/providers/edge_api/__init__.py, azext_edge/edge/providers/edge_api/dataflow.py, azext_edge/edge/providers/edge_api/mq.py, azext_edge/edge/providers/support/dataflow.py, azext_edge/edge/providers/support/mq.py, azext_edge/edge/providers/support_bundle.py, azext_edge/tests/edge/support/create_bundle_int/helpers.py, azext_edge/tests/edge/support/create_bundle_int/test_dataflow_int.py, azext_edge/tests/edge/support/test_support_unit.py
1. Update mqttbroker common label
2. Add dataflow capture in support bundle
3. Fix int failure for previous PR
Issue found on service side:
1. mqttbroker missing common label for aio-mq-fluent-bit pod
2. mqttbroker didn't remove old connecter resources
3. dataflow missing common label for aio-dataflow operator
1 pending on response, 2 will be fixed later. before the decision made I will capture them using other label/field
3 will be removed soon as well, before that I will keep support bundle as it is
---
This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact …
=> feat: Add dataflow capture in support bundle and update mqtt common label

.github/workflows/cluster_cleanup.yml
Ensure clean up pipeline also purges keyvaults. Purge allows us to reuse keyvault names (and avoid clashing between pipeline runs).
To allow purging, the no-wait for keyvault deletion has been removed. 
The general clean-up is kept as a backup for missed resources from `az iot ops delete` (ex: the command fails).
 
 Keyvaults after the cleanup pipeline:
 Note: the extra keyvault prefix input is temporary and will be removed once we have all keyvaults using the same one again (we had to diverge and use different ones due to clashes)
Note 2: Since the purge has a --no-wait, the purge may take some time and the results are not instantaneous.
---
This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the …
=> chore: improve clean up pipeline

azext_edge/edge/providers/support/dataflow.py, azext_edge/edge/providers/support/mq.py, azext_edge/tests/edge/support/create_bundle_int/test_mq_int.py, azext_edge/tests/edge/support/test_support_unit.py
1. update dataflow deployment to use the common label
2. update broker to capture fluent bit daemonset
verified all runtime resources are captured for broker and dataflow with latest image version
---
Azure IoT Operations CLI maintainers reserve the right to enforce any of …
=> fix: Update support bundle for broker and dataflow

azext_edge/edge/_help.py, azext_edge/edge/providers/check/base/node.py, azext_edge/edge/providers/check/base/user_strings.py, azext_edge/tests/edge/checks/base/test_nodes_unit.py
=> refactor: update `az iot ops check --pre` to not warn for multi-node clusters

azext_edge/edge/providers/check/deviceregistry.py, azext_edge/tests/edge/checks/test_deviceregistry_checks_unit.py
Added flag to prevent conditions to be add repeatedly everytime a new CRD instance is being iterated
example: when there are more than one CRD instance, now the repeat conditions got fixed:
---
Azure IoT Operations CLI maintainers reserve the right to enforce any of the …
=> fix: eliminate repeated target conditions in device registry check

azext_edge/tests/edge/checks/int/test_pre_post_int.py
=> test: fix pre-check integration test

azext_edge/edge/providers/support/billing.py, azext_edge/edge/providers/support/dataflow.py, azext_edge/tests/edge/support/conftest.py, azext_edge/tests/edge/support/test_support_unit.py
Since billing and meta resource share the same label, billing needs to be exclusive about the prefix it's capturing since both billing and meta resource has jobs and pods under AIO namespace(pods are already capturing the pod with prefix names stated, this pr is to fix the job)
---->
--- …
=> fix: exclude meta resource job from billing support bundle using prefix name

azext_edge/edge/providers/check/deviceregistry.py, azext_edge/tests/edge/checks/test_deviceregistry_checks_unit.py
endpoint should exist for the asset to be a thing
also endpoint profile uri -> endpoint profile
---
A PR is considered **ready for review** when all basic expectations have …
=> feat: ensure endpoint profile existance for asset checks

azext_edge/edge/_help.py, azext_edge/edge/common.py, azext_edge/edge/params.py, azext_edge/edge/providers/check/base/check_manager.py, azext_edge/edge/providers/check/base/display.py, azext_edge/edge/providers/check/base/node.py, azext_edge/edge/providers/check/common.py, azext_edge/edge/providers/check/dataflow.py, azext_edge/edge/providers/checks.py, azext_edge/edge/providers/orchestration/template.py, azext_edge/edge/providers/support/dataflow.py, azext_edge/tests/edge/checks/base/test_check_manager_unit.py, azext_edge/tests/edge/checks/base/test_display_unit.py, azext_edge/tests/edge/checks/conftest.py, azext_edge/tests/edge/checks/int/helpers.py, azext_edge/tests/edge/checks/int/test_dataflow_int.py, azext_edge/tests/edge/checks/int/test_pre_post_int.py, azext_edge/tests/edge/checks/test_dataflow_checks_unit.py
=> chore: merge dev into feature/0.7.0

azext_edge/edge/vendor/clients/iotopsmgmt/_client.py, azext_edge/edge/vendor/clients/iotopsmgmt/operations/_operations.py, azext_edge/edge/vendor/clients/resourcesmgmt/operations/_operations.py
* Since spec changed for same API.
* Remove deprecated escape sequence from resource client.
=> refactor: Refresh embedded aio client doc strings

azext_edge/edge/commands_edge.py, azext_edge/edge/params.py, azext_edge/edge/providers/orchestration/targets.py, azext_edge/edge/providers/orchestration/template.py, azext_edge/tests/edge/orchestration/resources/test_schema_registry_int.py
- Starting application for int based parameters that define min / max.
- Can be expanded as necessary.
- One gap is error presents model config name rather than CLI parameter but IMO these are clear enough for this first go.
- Fixes some issues in SR IT.
=> refactor: Follow up. Adds param validation pattern using template languageVersion 2 model.

azext_edge/edge/common.py, azext_edge/edge/providers/support_bundle.py, azext_edge/tests/edge/support/create_bundle_int/helpers.py, azext_edge/tests/edge/support/create_bundle_int/test_auto_int.py, azext_edge/tests/edge/support/create_bundle_int/test_schemaregistry_int.py, azext_edge/tests/edge/support/test_support_unit.py, azext_edge/tests/helpers.py
=> fix: add schema registry under --svc for support bundle

azext_edge/edge/common.py, azext_edge/edge/providers/check/base/resource.py, azext_edge/tests/edge/checks/base/test_resource_unit.py
"Warning" was not found in ResourceState cause it to be matched as an unknown status
1. therefore adding warning under ResourceState 
2. make everything lowercased before doing the status matching
3. Added unitest to make sure things working as expected
---
Azure IoT …
=> fix: fix status matching for check

.devcontainer/post_create_commands.sh
=> chore: update codespace cluster creation script

azext_edge/edge/_help.py, azext_edge/edge/commands_edge.py, azext_edge/edge/params.py, azext_edge/edge/providers/orchestration/deletion.py, azext_edge/edge/providers/orchestration/resource_map.py, azext_edge/edge/providers/orchestration/work.py, azext_edge/tests/edge/orchestration/test_resource_map_unit.py
* Latter supported by refactor of direct usage of `connected cluster` to `resource_map`.
* Don't show custom location node if no corresponding resources exist.
=> refactor: re-add cluster lookup to delete, show tree visual after init.

azext_edge/constants.py, azext_edge/edge/_help.py, azext_edge/edge/commands_edge.py, azext_edge/edge/commands_secretsync.py, azext_edge/edge/params.py, azext_edge/edge/providers/orchestration/resources/instances.py, azext_edge/edge/providers/orchestration/template.py
* Comments on elements that need more thought.
=> refactor: federation improvements + template increment.

azext_edge/tests/edge/orchestration/resources/test_schema_registry_int.py
Note the error is from delete in schema registry returning a weird value
---
A PR is considered **ready for review** when all basic expectations have been met (or do not …
=> test: update schema registry integration tests to use the resource group region

azext_edge/edge/providers/check/mq.py, azext_edge/tests/edge/checks/test_mq_checks_unit.py
bug fixed and added missing test for service check
before:
after:
---
=> fix: check ingress rule for load balancer typed service not showing correct value

azext_edge/edge/providers/check/base/resource.py, azext_edge/tests/edge/checks/base/test_resource_unit.py, azext_edge/tests/edge/checks/test_mq_checks_unit.py
note: description will only show in level 2
---
=> fix: update broker runtime status description structure in check for latest CRD

azext_edge/tests/edge/support/create_bundle_int/helpers.py
=> fix: secretstore support bundle test when there is no crd

azext_edge/edge/_help.py, azext_edge/edge/commands_assets.py, azext_edge/edge/params.py, azext_edge/edge/providers/rpsaas/adr/assets.py, azext_edge/edge/providers/rpsaas/adr/user_strings.py, azext_edge/tests/edge/rpsaas/adr/conftest.py, azext_edge/tests/edge/rpsaas/adr/test_assets_unit.py
Make sure there is a unique name for events/data-points
some help updates too like default for dataset name
---
A PR is considered **ready for review** when all basic …
=> feat: ensure "name" is prioritized for asset events and data-points

azext_edge/tests/edge/init/int/test_init_int.py, azext_edge/tests/edge/orchestration/resources/test_instance_int.py
=> test: separate instance lifecycle tests from init

azext_edge/edge/_help.py, azext_edge/edge/providers/orchestration/resources/schema_registries.py, azext_edge/edge/providers/orchestration/rp_namespace.py, azext_edge/tests/edge/conftest.py, azext_edge/tests/edge/init/conftest.py, azext_edge/tests/edge/init/test_base_unit.py, azext_edge/tests/edge/orchestration/resources/test_schema_registry_unit.py
Add in the rp register helper into create before everything else. Registering just the ADR for good security practices.
I am keeping the init rp register JUST in case something gets unregistered.
---
Azure IoT Operations CLI maintainers reserve the right to enforce any of …
=> feat: register required resource providers in `az iot ops schema registry create`

azext_edge/tests/edge/support/create_bundle_int/test_arccontainerstorage_int.py
=> fix(test): fix prefix for esa -> acsa in support bundle tests

azext_edge/edge/_help.py, azext_edge/edge/commands_connector.py, azext_edge/edge/params.py, azext_edge/edge/providers/orchestration/resources/connector/opcua/certs.py, azext_edge/tests/edge/orchestration/resources/connector/opcua/conftest.py, azext_edge/tests/edge/orchestration/resources/connector/opcua/test_opcua_certs_issuer_unit.py, azext_edge/tests/edge/orchestration/resources/connector/opcua/test_opcua_certs_trust_unit.py
=> fix: remove prompts in `az iot ops connector opcua`

azext_edge/edge/providers/orchestration/resources/connector/opcua/certs.py, azext_edge/tests/edge/orchestration/resources/connector/opcua/test_opcua_certs_client_unit.py, azext_edge/tests/edge/orchestration/resources/connector/opcua/test_opcua_certs_issuer_unit.py, azext_edge/tests/edge/orchestration/resources/connector/opcua/test_opcua_certs_trust_unit.py
this way will fix the issue when there is already a resource with same name existed in rg with other aio instance
---
A PR is considered **ready for review** when all basic …
=> fix: cert management look up existing resource use cl + rg instead of just rg

azext_edge/edge/providers/orchestration/upgrade.py
=> fix: changes for `az iot ops upgrade` display text

azext_edge/edge/providers/orchestration/resources/schema_registries.py, azext_edge/tests/edge/orchestration/resources/test_schema_unit.py
=> fix: change schema version error handling to look at error codes

.github/workflows/int_test.yml, azext_edge/azext_metadata.json, azext_edge/constants.py, azext_edge/edge/_help.py, azext_edge/edge/command_map.py, azext_edge/edge/commands_edge.py, azext_edge/edge/params.py, azext_edge/edge/providers/orchestration/__init__.py, azext_edge/edge/providers/orchestration/host.py, azext_edge/tests/edge/conftest.py
* To match the connector commands, the secretsync commands will align on --instance over --name, when referring to instance, however -n is an option added to both as a happy medium.
=> feat!: remove verify-host, hide upgrade, re-classify preview cmds

azext_edge/edge/providers/orchestration/resources/schema_registries.py, azext_edge/tests/edge/orchestration/resources/conftest.py, azext_edge/tests/edge/orchestration/resources/test_schema_registry_unit.py
* Motivation: SR create and the way assign role assignment is implemented in the client are idempotent. The operation is also relatively fast. The change is intended to net a more consistent outcome as SR cannot function properly without the role assignment.
* Improve unit test pattern.
=> feat!: SR create role assignment failure will throw an error vs warning. 

azext_edge/edge/_help.py, azext_edge/edge/common.py, azext_edge/edge/providers/edge_api/__init__.py, azext_edge/edge/providers/edge_api/openservicemesh.py, azext_edge/edge/providers/support/openservicemesh.py, azext_edge/edge/providers/support_bundle.py, azext_edge/tests/edge/support/create_bundle_int/helpers.py, azext_edge/tests/edge/support/create_bundle_int/test_auto_int.py, azext_edge/tests/edge/support/create_bundle_int/test_openservicemesh_int.py, azext_edge/tests/edge/support/test_openservicemesh_unit.py
=> feat: add openservice mesh resources in support bundle

.github/workflows/int_test.yml, azext_edge/edge/providers/rpsaas/adr/asset_endpoint_profiles.py, azext_edge/tests/edge/support/create_bundle_int/test_mq_int.py
Separate supportbundle/edge side testing vs rpsaas
add in prefix for mq testing
---
A PR is considered **ready for review** when all basic expectations have been met (or do …
=> test: Update support bundle tests

azext_edge/edge/params.py
* Last changeset hid upgrade params, however --*-config is still applicable and useful for patching arc extension config post deployment.
=> refactor: keep --*-config visible

azext_edge/tests/edge/support/create_bundle_int/helpers.py, azext_edge/tests/edge/support/create_bundle_int/test_auto_int.py
=> test: fix support bundle acstor/acs namespace issues

azext_edge/edge/providers/orchestration/resources/connector/opcua/certs.py, azext_edge/tests/edge/orchestration/resources/connector/opcua/test_opcua_certs_client_unit.py
Should only patch the modified properties instead of all properties
---
=> fix: fix patch in client cert AIO extension update

azext_edge/edge/params.py, azext_edge/edge/providers/orchestration/clone.py, azext_edge/tests/edge/orchestration/resources/conftest.py, azext_edge/tests/edge/orchestration/resources/test_broker_authns_unit.py, azext_edge/tests/edge/orchestration/resources/test_broker_authzs_unit.py, azext_edge/tests/edge/orchestration/resources/test_broker_listeners_unit.py, azext_edge/tests/edge/orchestration/resources/test_brokers_unit.py, azext_edge/tests/edge/orchestration/resources/test_dataflow_endpoints_unit.py, azext_edge/tests/edge/orchestration/resources/test_dataflow_profiles_unit.py, azext_edge/tests/edge/orchestration/resources/test_dataflows_unit.py, azext_edge/tests/edge/orchestration/test_clone_unit.py
- New root deployment param `location`, (default from model instance)
- All tracked resources use the param.
- New root deployment param `schemaRegistryId`, (default from model instance)
- It is an object type because parts of the resource Id are re-used for a role assignment sub deployment
- New root deployment param `applyRoleAssignments`, bool with default `true`.
- Instance feature mode not supporting reapplying its own representation (mode = "")
- When mode="" the property will be omitted.
=> feat: set of initial clone follow ups, more parameterization
